### ISSUE TITLE
Failed to resolve directive: paginate (found in component:

### ISSUE THREAD

**Issue by zchrissirhcz** [TahaSh/vue-paginate#16]
I'm using `vue-paginate` in my `.vue` component file. I follow this repo's readme that import vue-paginate in `<script></script>` and add it to `components` part. However, using this code can not work(copied and adapted from readme):

```
<template>
  <div class="hello">
    <section v-paginate:2="posts" limit="5">
      <ul v-for="post in posts">
        <li>{{ post }}</li>
      </ul>
    </section>

    <ul class="links">
      <li v-for="postLink in limitedPostsLinks">
        <a :class="{active: currentPostsPage == postLink}" href="#" @click="changePostsPage(postLink)">{{ postLink }}</a>
      </li>
    </ul>
  </div>
</template>

<script>
import VuePaginate from 'vue-paginate'
export default {
  components: {
    VuePaginate
  },
  data () {
    return {
      posts: ['PHP', 'JavaScript', 'HTML', 'CSS', 'Ruby', 'Python']
    }
  }
}
</script>
``` 

Chrome's console says:
![image](https://cloud.githubusercontent.com/assets/3831847/18376555/d69c44b6-7692-11e6-8a34-fcb5e6afff35.png)

How can I adjust my code?

**Comment by TahaSh** [comment]
@zchrissirhcz You're getting this error because you've forgotten to install it, by doing this (usually in your `main.js`):

``` js
Vue.use(VuePaginate)
```

And please note that this plugin isn't a component; it's a directive. So, there's no need to register it in your components list.

So, your `<script>`, can become like this:

```
<script>
export default {
  data () {
    return {
      posts: ['PHP', 'JavaScript', 'HTML', 'CSS', 'Ruby', 'Python']
    }
  }
}
</script>
```

This should fix it! Thanks for the question :).
