### ISSUE TITLE
setting up currentPage programmatically 

### ISSUE THREAD

**Issue by eybarta** [TahaSh/vue-paginate#37]
Hi,

first off, great work on the previous issue I've posted! thank you.

I would like to be able to 'goToPage(x)'. I saw in vue-paginate code
the computed property 'currentPage' has a setter also, anyway you could
expose it outwards so I could do something like:
`$pager.currentPage = 1`

thx

**Comment by grelca** [comment]
also looking for this, as i'm finding it very inconsistent that the page reverts to 1 in the case that i filter the item list and there are no items on the current page.

right now i'm working around this with the following code:

`// don't click the 0 in initial loading..
if($('ul.paginate-links > li.number > a').html() == "1")
	$('ul.paginate-links > li.number > a')[0].click();`

and it works just fine, but i'd _love_ a more elegant approach. also since i'm doing it that way, i can't use the hide with only a single page option.

**Comment by juanpasolano** [comment]
Having the same situation.

**Comment by TahaSh** [comment]
This feature is now included in version 3.5.0 ([see how to use it](https://github.com/TahaSh/vue-paginate#navigate-pages-programmatically)). Thanks @juanpasolano for your suggestion, but I recommend using the way described in the docs.
