### ISSUE TITLE
Set a limit to the visible pages links

### ISSUE THREAD

**Issue by DannyFeliz** [TahaSh/vue-paginate#5]
Hi, I was wondering how can I set a limit to the number of pages that will be visible when the pagination is displayed?

e.g. I want to display just 4 pages and then just display three dots that display the next 4 pages

![2016-05-03 16_36_43-bootpag - dynamic pagination jquery plugin](https://cloud.githubusercontent.com/assets/5460365/14997757/571977bc-114e-11e6-9fac-f6654e818cc0.png)

**Comment by TahaSh** [comment]
Just to confirm, do you want to display the next 4 pages when the user clicks on the three dots? If this is what you want, I think this won't be very helpful, because if the user keeps clicking them, he'll end up with all links shown up; and I think this defeats the whole purpose of limiting the links.

Is that what you want? If not, what do you mean by displaying the next 4 pages?

**Comment by DannyFeliz** [comment]
@TahaSh What I want is something like this (Looks for the **"Advanced example"** section) http://botmonster.com/jquery-bootpag/#.VypQwIQrKUl

**Comment by MrFather** [comment]
@TahaSh I really need this feature, in my work we're using it then I realized that I can't set a limit to the visible pages. Please fix it :pray:

**Comment by TahaSh** [comment]
@MrFather Don't worry, this will be added (at most) by the end of tomorrow.

**Comment by TahaSh** [comment]
Version 2.0.0 is now released! It includes this feature: https://github.com/TahaSh/vue-paginate#limit-the-number-of-displayed-links

**Comment by DannyFeliz** [comment]
@TahaSh Thank you man, I've been waiting for this :dancer:
