### ISSUE TITLE
Unable to update full list property when using component.

### ISSUE THREAD

**Issue by Lucassith** [TahaSh/vue-paginate#9]
Hello, I dynamically fetch the data from my API on vue's ready function. Before that my list contains only one null element. I also use a component to show the data.

On ready I get from my API 10 elements and I paginate the results to show only 4 of them. This works anytime, however if I try to use next, prev or change function it will show the null value from the beggining. 

I tried to instantiate Vue with 3 elements on the list ["test1", "test2", "test3"] and after changing the page it will show only those 3 elements not paginated data from API.

Also if you use full[listName] in the component's v-for it will not show the data fetched later via API but the one you instantiated with vue.

I tried to use 
```
this.fullOffers = response.data;
self.$set("fullOffers", response.data);
```
on the parent element with no luck. I think that the component's full<listName> data is not being updated.

**Comment by Lucassith** [comment]
Here is the event list. 

![fulllistpagination](https://cloud.githubusercontent.com/assets/7236601/15992033/bc7fc9f6-30c2-11e6-93a5-1b813fc8a49c.png)

As you can see the fullOffers prop is being updated only at the beggining and it does not change after the data being fetched via API call. I am unable to update it from the parent's scope.

**Comment by TahaSh** [comment]
Hey @Lucassith! I'm not sure I fully understand the context of your problem, but I guess here's the solution.

So, let's take the example of `langs` list. Let's say that I want to fetch the list from an API, and I want to pass the fetched data to a component which will paginate them and display them.

This means first I need to define that component (I'll call it `test-component`):

``` js
Vue.component('testComponent', {
  template: '#langs-template',
  
  props: ['fullLangs'],

  data () {
    return {
      langs: []
    }
  }
})
```

Note how I accept the `fullLangs` as a prop instead of `langs` (that's the trick to make it work).

And here's the template for the component:

``` html
<template id="langs-template">
  <!-- data -->
  <ul v-paginate:3="langs">
    <li v-for="lang in langs">
      {{ lang }}
    </li>
  </ul>

  <!-- links -->
  <a @click="prevLangsPage()" href="#">
    Prev
  </a>
  |
  <a @click="nextLangsPage()" href="#">
    Next
  </a>
</template>
```

Now in your parent component you'll need to use that component like this:

``` html
<test-component :full-langs="fetchedLangs"></test-component>
```

Notice how I passed an array called `fetchedLangs`, which we haven't created yet. Let's do this now in the parent component:

``` js
new Vue({
  el: '#app',
  data: {
    fetchedLangs: []
  },

  ready () {
    this.$http.get('/langs')
      .then(function (response) {
        this.fetchedLangs = response.data
      })
  }
});
```

With that, everything should work as expected, because when the `fetchedLangs` are filled with the data from the API it'll be automatically assigned to `fullLangs` in the child component which will change the full version of the list, so it gets paginated properly by the plugin.

Hope this solves your problem.

Thanks for using the plugin :).

**Comment by Lucassith** [comment]
Yeah you're right, now it works, thank you! :+1: 

Also please take a look on the first issue "inside a component using props". I was following your comment there.

Great plugin, Thank you!
